// <auto-generated/>
// Generated from Il2CppDefaults.cs — do not edit manually.

#pragma once

struct Il2CppClass;
struct Il2CppImage;
struct MethodInfo;

typedef struct Il2CppDefaults
{
    Il2CppImage *corlib;
    Il2CppImage *corlib_gen;
    Il2CppClass *object_class;
    Il2CppClass *byte_class;
    Il2CppClass *void_class;
    Il2CppClass *void_ptr_class;
    Il2CppClass *boolean_class;
    Il2CppClass *sbyte_class;
    Il2CppClass *int16_class;
    Il2CppClass *uint16_class;
    Il2CppClass *int32_class;
    Il2CppClass *uint32_class;
    Il2CppClass *int_class;
    Il2CppClass *uint_class;
    Il2CppClass *int64_class;
    Il2CppClass *uint64_class;
    Il2CppClass *single_class;
    Il2CppClass *double_class;
    Il2CppClass *char_class;
    Il2CppClass *string_class;
    Il2CppClass *enum_class;
    Il2CppClass *array_class;
    Il2CppClass *delegate_class;
    Il2CppClass *multicastdelegate_class;
#if !MONO_NET_BCL
    Il2CppClass *asyncresult_class;
    Il2CppClass *manualresetevent_class;
#endif
    Il2CppClass *typehandle_class;
    Il2CppClass *fieldhandle_class;
    Il2CppClass *methodhandle_class;
    Il2CppClass *systemtype_class;
    Il2CppClass *monotype_class;
    Il2CppClass *exception_class;
    Il2CppClass *threadabortexception_class;
    Il2CppClass *thread_class;
#if !MONO_NET_BCL
    Il2CppClass *internal_thread_class;
#endif
    Il2CppClass *appdomain_class;
    Il2CppClass *appdomain_setup_class;
#if MONO_NET_BCL
    Il2CppClass *app_context_class;
    Il2CppClass *assembly_load_context_class;
#endif
    Il2CppClass *member_info_class;
    Il2CppClass *field_info_class;
    Il2CppClass *method_info_class;
    Il2CppClass *property_info_class;
    Il2CppClass *event_info_class;
    Il2CppClass *stringbuilder_class;
#if MONO_NET_BCL
    Il2CppClass *mono_stack_frame_class;
    Il2CppClass *stack_trace_class;
#endif
    Il2CppClass *stack_frame_class;
    Il2CppClass *marshal_class;
    Il2CppClass *typed_reference_class;
    Il2CppClass *generic_ilist_class;
    Il2CppClass *generic_icollection_class;
    Il2CppClass *generic_ienumerable_class;
    Il2CppClass *generic_ireadonlylist_class;
    Il2CppClass *generic_ireadonlycollection_class;
    Il2CppClass *generic_readonlycollection_class;
    Il2CppClass *runtimetype_class;
    Il2CppClass *generic_nullable_class;
    Il2CppClass *il2cpp_com_object_class;
    Il2CppClass *attribute_class;
#if MONO_NET_BCL
    Il2CppClass *runtime_customattribute_data_class;
#endif
#if !MONO_NET_BCL
    Il2CppClass *customattribute_data_class;
#endif
    Il2CppClass *customattribute_typed_argument_class;
    Il2CppClass *customattribute_named_argument_class;
    Il2CppClass *version;
    Il2CppClass *culture_info;
#if !MONO_NET_BCL
    Il2CppClass *async_call_class;
#endif
    Il2CppClass *assembly_class;
    Il2CppClass *assembly_name_class;
    Il2CppClass *mono_assembly_name_class;
    Il2CppClass *parameter_info_class;
    Il2CppClass *module_class;
    Il2CppClass *dbnull_class;
    Il2CppClass *error_wrapper_class;
    Il2CppClass *missing_class;
    Il2CppClass *value_type_class;
    Il2CppClass *stream_class;
#if !MONO_NET_BCL
    Il2CppClass *threadpool_wait_callback_class;
    const MethodInfo *threadpool_perform_wait_callback_method;
    Il2CppClass *mono_method_message_class;
#endif
    Il2CppClass *ireference_class;
    Il2CppClass *ireferencearray_class;
    Il2CppClass *ikey_value_pair_class;
    Il2CppClass *key_value_pair_class;
    Il2CppClass *windows_foundation_uri_class;
    Il2CppClass *windows_foundation_iuri_runtime_class_class;
    Il2CppClass *system_uri_class;
    Il2CppClass *system_guid_class;
    Il2CppClass *sbyte_shared_enum;
    Il2CppClass *int16_shared_enum;
    Il2CppClass *int32_shared_enum;
    Il2CppClass *int64_shared_enum;
    Il2CppClass *byte_shared_enum;
    Il2CppClass *uint16_shared_enum;
    Il2CppClass *uint32_shared_enum;
    Il2CppClass *uint64_shared_enum;
    Il2CppClass *il2cpp_shared_object_type;
    Il2CppClass *il2cpp_fully_shared_type;
    Il2CppClass *il2cpp_fully_shared_struct_type;
    const MethodInfo *thread_sleep_internal_method;
    const MethodInfo *runtime_type_get_type_method;
#if MONO_NET_BCL
    Il2CppClass *idynamic_interface_castable;
#endif
} Il2CppDefaults;
