// <auto-generated/>
// Generated from Il2CppDefaults.cs — do not edit manually.

#pragma once

#include "il2cpp-class-internals.h"

static inline void AssertRequiredIl2CppDefaultsAreNotNull()
{
    IL2CPP_ASSERT(il2cpp_defaults.object_class);
    IL2CPP_ASSERT(il2cpp_defaults.byte_class);
    IL2CPP_ASSERT(il2cpp_defaults.void_class);
    IL2CPP_ASSERT(il2cpp_defaults.boolean_class);
    IL2CPP_ASSERT(il2cpp_defaults.sbyte_class);
    IL2CPP_ASSERT(il2cpp_defaults.int16_class);
    IL2CPP_ASSERT(il2cpp_defaults.uint16_class);
    IL2CPP_ASSERT(il2cpp_defaults.int32_class);
    IL2CPP_ASSERT(il2cpp_defaults.uint32_class);
    IL2CPP_ASSERT(il2cpp_defaults.int_class);
    IL2CPP_ASSERT(il2cpp_defaults.uint_class);
    IL2CPP_ASSERT(il2cpp_defaults.int64_class);
    IL2CPP_ASSERT(il2cpp_defaults.uint64_class);
    IL2CPP_ASSERT(il2cpp_defaults.single_class);
    IL2CPP_ASSERT(il2cpp_defaults.double_class);
    IL2CPP_ASSERT(il2cpp_defaults.char_class);
    IL2CPP_ASSERT(il2cpp_defaults.string_class);
    IL2CPP_ASSERT(il2cpp_defaults.enum_class);
    IL2CPP_ASSERT(il2cpp_defaults.array_class);
    IL2CPP_ASSERT(il2cpp_defaults.delegate_class);
    IL2CPP_ASSERT(il2cpp_defaults.multicastdelegate_class);
#if !MONO_NET_BCL
    IL2CPP_ASSERT(il2cpp_defaults.asyncresult_class);
    IL2CPP_ASSERT(il2cpp_defaults.manualresetevent_class);
#endif
    IL2CPP_ASSERT(il2cpp_defaults.systemtype_class);
    IL2CPP_ASSERT(il2cpp_defaults.exception_class);
    IL2CPP_ASSERT(il2cpp_defaults.thread_class);
#if !MONO_NET_BCL
    IL2CPP_ASSERT(il2cpp_defaults.internal_thread_class);
#endif
    IL2CPP_ASSERT(il2cpp_defaults.appdomain_class);
#if MONO_NET_BCL
    IL2CPP_ASSERT(il2cpp_defaults.app_context_class);
    IL2CPP_ASSERT(il2cpp_defaults.assembly_load_context_class);
#endif
    IL2CPP_ASSERT(il2cpp_defaults.member_info_class);
    IL2CPP_ASSERT(il2cpp_defaults.field_info_class);
    IL2CPP_ASSERT(il2cpp_defaults.method_info_class);
    IL2CPP_ASSERT(il2cpp_defaults.property_info_class);
    IL2CPP_ASSERT(il2cpp_defaults.runtimetype_class);
    IL2CPP_ASSERT(il2cpp_defaults.generic_nullable_class);
    IL2CPP_ASSERT(il2cpp_defaults.il2cpp_com_object_class);
    IL2CPP_ASSERT(il2cpp_defaults.attribute_class);
    IL2CPP_ASSERT(il2cpp_defaults.version);
    IL2CPP_ASSERT(il2cpp_defaults.culture_info);
#if !MONO_NET_BCL
    IL2CPP_ASSERT(il2cpp_defaults.async_call_class);
#endif
    IL2CPP_ASSERT(il2cpp_defaults.assembly_class);
    IL2CPP_ASSERT(il2cpp_defaults.dbnull_class);
    IL2CPP_ASSERT(il2cpp_defaults.missing_class);
    IL2CPP_ASSERT(il2cpp_defaults.value_type_class);
#if !MONO_NET_BCL
    IL2CPP_ASSERT(il2cpp_defaults.threadpool_wait_callback_class);
    IL2CPP_ASSERT(il2cpp_defaults.mono_method_message_class);
#endif
    IL2CPP_ASSERT(il2cpp_defaults.key_value_pair_class);
    IL2CPP_ASSERT(il2cpp_defaults.system_guid_class);
}
