name: update

permissions:
  contents: write

on:
  push:
    branches: [ "master" ]
  workflow_call:

jobs:
  update:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref == 'refs/heads/archive' && 'master' || '' }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Build archive
        run: dotnet run -c Release

      - name: Push
        run: |
          cd ./archive
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          # HACK: A special PUSH_TOKEN is needed here because we can't allow the workflows permission in normal GITHUB_TOKEN
          git remote add origin https://x-access-token:${{ secrets.PUSH_TOKEN }}@github.com/${{ github.repository }}
          git push --tags --force -u origin archive
